### ISSUE TITLE
CLI PANICS when config is a file instead of directory

### ISSUE THREAD

**Issue by bupd** [goharbor/harbor-cli#264]
### To Reproduce this issue
1. Remove the old config file
2. create a directory in place of config file. with same name of config file
3. this causes the cli to panic

## Expected Behaviour
Instead of panicking CLI should return error there is a directory in the place of config file.

 
## Error output
(PANIC)
```bash
> harbor-dev artifacts list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa2ca07]

goroutine 1 [running]:
github.com/goharbor/harbor-cli/cmd/harbor/root.InitConfig()
        /src/cmd/harbor/root/cmd.go:34 +0x147
github.com/spf13/cobra.(*Command).preRun(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1019
github.com/spf13/cobra.(*Command).execute(0xc00036ec08, {0x1245340, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:929 +0x5a2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000216608)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.main()
        /src/cmd/harbor/main.go:10 +0x18
       
   ```

**Comment by qcserestipy** [comment]
@bupd is this in the default home directory? Does it also happen after commit 0d1f474 to main?
I can have a look and try to reproduce this issue

**Comment by bupd** [comment]
@Standing-Man 
### To Reproduce this issue
Remove the old config file
create a directory in place of config file. with same name of config file
this causes the cli to panic

### Expected Behaviour
Instead of panicking CLI should return error there is a directory in the place of config file.

**Comment by Standing-Man** [comment]
Thank you for providing more details on how to reproduce this issue. I will try to figure out what is going wrong.

**Comment by mviswanathsai** [comment]
I did the following:
```bash
mviswanathsai@pop-os:~/.config/harbor-cli$ rm config.yaml
mviswanathsai@pop-os:~/.config/harbor-cli$ mkdir config.yaml
mviswanathsai@pop-os:~/.config/harbor-cli$ ls
config.yaml
mviswanathsai@pop-os:~/.config/harbor-cli$ cd ..
mviswanathsai@pop-os:~/.config$ cd ..
mviswanathsai@pop-os:~$ cd harbor-cli/
mviswanathsai@pop-os:~/harbor-cli$ ./harbor-cli project list 
FATA[0000] error reading config file: read /home/mviswanathsai/.config/harbor-cli/config.yaml: is a directory. Please ensure the config file exists. 
```

And the output seems to be what we expect. Is this issue fixed now?

**Comment by bupd** [comment]
This is still not fixed.

**Comment by rizul2108** [comment]
@bupd Can I take this one?
