### ISSUE TITLE
Panic on Harbor login Ctrl+C keyboard interrupt crashes the code

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#36]
Ctrl+C keyboard interrupt crashes the code on login.
Trying to log in. 

```
./harbor login 8gears.container-registry.com
```
now I hit aboard (CTRL+C)

```
panic: user aborted

goroutine 1 [running]:
github.com/goharbor/harbor-cli/pkg/views/login.CreateView(0x14000408240)
        /Users/vadim/Development/container-registry/harbor-cli/pkg/views/login/create.go:61 +0x3e8
github.com/goharbor/harbor-cli/cmd/harbor/root.createLoginView(0x0?)
        /Users/vadim/Development/container-registry/harbor-cli/cmd/harbor/root/login.go:77 +0x44
github.com/goharbor/harbor-cli/cmd/harbor/root.LoginCommand.func1(0x1400022eb00?, {0x140004064a0?, 0x4?, 0x1008fa4db?})
        /Users/vadim/Development/container-registry/harbor-cli/cmd/harbor/root/login.go:48 +0x174
github.com/spf13/cobra.(*Command).execute(0x140001a0c00, {0x14000406470, 0x1, 0x1})
        /Users/vadim/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x140001a0600)
        /Users/vadim/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(0x100e522b8?)
        /Users/vadim/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x1c
main.main()
        /Users/vadim/Development/container-registry/harbor-cli/cmd/harbor/main.go:10 +0x20
```

**Comment by amands98** [comment]
I will fix this.
